jms_serializer:
    metadata:
        directories:
            LhgPayroll:
                namespace_prefix: "KimaiPlugin\\LhgPayrollBundle"
                path: "@LhgPayrollBundle/Resources/config/serializer"
        # warmup:
        #     paths:
        #         included:
        #             - "%kernel.root_dir%/../var/plugins/LhgPayrollBundle/Entity/"
