services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
    
    KimaiPlugin\LhgPayrollBundle\Service\PayrollCalculatorService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    KimaiPlugin\LhgPayrollBundle\:
        resource: '../../*'
        exclude: '../../{Resources}' 
    
    KimaiPlugin\LhgPayrollBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        # arguments:
        #     $dataDirectory: "%kimai.data_dir%" 